### ISSUE TITLE
⚠️  ‼️ missing WIF CHARACTERS

### ISSUE THREAD

**Issue by Handsomekaizer** [Pymmdrza/LTC_Generator#1]
Hello sir
Sorry to bother I was just going through your repo to see if you could help me. The problem I have is with my wallet private key characters, I mistakenly damaged the piece of paper I wrote it on, so I was wondering if you could help me write a program that will brute Force all the 10 missing characters very fast and find the correct characters and in return I will make a donation of 2 BTC to you if I find the correct keys

**Comment by nsiqwe** [comment]
Are you missing 10 characters ? You can not do this with 2 characters. If you have more you can contact to me on telegram: @singuyen

**Comment by YashvirGaming** [comment]
@nsiqwe what about Balance Checker ?
does this generator LTC shows Balance too

**Comment by Pymmdrza** [comment]
I hope you didn't waste your money by some editors.

⚠️ To communicate with me and do customized and specialized work, please proceed only through the following, otherwise we cannot accept the responsibility of any communication with fraudulent people here.

### Telegram id : [@MrPyMmdrza](https://mrpymmdrza.t.me 'Telegram ID MrPyMmdrza')

### Telegram Channel : [@Cryptoixer](https://cryptoixer.t.me 'cryptoixer official channel on telegram')

### Official Website : [Mmdrza.Com](https://mmdrza.com 'official website mmdrza')

### Email : Pymmdrza@gmail.com

### Medium : [mdrza.Medium.com](https://mdrza.medium.com 'Medium Page Mmdrza')
